name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  RUST_LOG: INFO

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose

      - name: "Check"
        run: cargo check --all
      - name: "Build  (Without Python node as it is build with maturin)"
        run: cargo build --all
      - name: "Test"
        run: cargo test --all

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose

      - name: "Clippy"
        run: cargo clippy --all

  rustfmt:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: "rustfmt"
        run: cargo fmt --all -- --check

  check-license:
    name: "License Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: buildjet
          cache-on-failure: true
          # only save caches for `main` branch
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - run: cargo install cargo-lichking
      - name: "Check dependency licenses"
        run: cargo lichking check
